# Generated by Django 6.0.2 on 2026-02-20 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ens', models.CharField(max_length=45, unique=True)),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('prenoms', models.CharField(blank=True, max_length=225, null=True)),
                ('email', models.EmailField(blank=True, max_length=45, null=True)),
                ('departement', models.CharField(blank=True, max_length=225, null=True)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('specialite', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Enseignants',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_carte', models.CharField(max_length=45, unique=True)),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('prenoms', models.CharField(blank=True, max_length=225, null=True)),
                ('email', models.EmailField(blank=True, max_length=45, null=True)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('filiere', models.CharField(blank=True, max_length=45, null=True)),
                ('departement', models.CharField(blank=True, choices=[('BDGL', 'BDGL'), ('RSI', 'RSI'), ('SI', 'SI')], max_length=10, null=True)),
                ('annee_entree', models.IntegerField(blank=True, null=True)),
                ('date_naiss', models.DateField(blank=True, null=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='nosqlproject.enseignant')),
            ],
            options={
                'db_table': 'Etudiants',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_cours', models.CharField(max_length=45, unique=True)),
                ('intitule', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=225, null=True)),
                ('credit_ects', models.IntegerField(blank=True, null=True)),
                ('semestre', models.CharField(blank=True, max_length=45, null=True)),
                ('niveau', models.CharField(blank=True, max_length=45, null=True)),
                ('departement', models.CharField(blank=True, choices=[('Anglais', 'Anglais'), ('Histoire', 'Histoire'), ('Geologique', 'Geologique')], max_length=10, null=True)),
                ('prerequis', models.CharField(blank=True, max_length=225, null=True)),
                ('etudiants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='nosqlproject.etudiant')),
            ],
            options={
                'db_table': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cours', models.DateField(blank=True, null=True)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nosqlproject.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nosqlproject.etudiant')),
            ],
            options={
                'db_table': 'Cours_has_Etudiants',
                'unique_together': {('cours', 'etudiant')},
            },
        ),
    ]
