# Generated by Django 6.0.2 on 2026-02-21 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosqlproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='enseignant',
        ),
        migrations.AddField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='nosqlproject.enseignant'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='departement',
            field=models.CharField(blank=True, choices=[('Anglais', 'Anglais'), ('Histoire', 'Histoire'), ('Geographie', 'Geographie')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cours',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='cours',
            name='etudiants',
        ),
        migrations.AlterField(
            model_name='cours',
            name='prerequis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='departement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='prenoms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.CharField(blank=True, choices=[('BDGL', 'BDGL'), ('RSI', 'RSI'), ('SI', 'SI')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='prenoms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='cours',
            table=None,
        ),
        migrations.AlterModelTable(
            name='enseignant',
            table=None,
        ),
        migrations.AlterModelTable(
            name='etudiant',
            table=None,
        ),
        migrations.AlterModelTable(
            name='inscription',
            table=None,
        ),
        migrations.AddField(
            model_name='cours',
            name='etudiants',
            field=models.ManyToManyField(related_name='cours', through='nosqlproject.Inscription', to='nosqlproject.etudiant'),
        ),
    ]
