# Generated by Django 6.0.2 on 2026-02-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosqlproject', '0002_remove_etudiant_departement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='departement',
            field=models.CharField(blank=True, choices=[('Anglais', 'Anglais'), ('Histoire', 'Histoire'), ('Geographie', 'Geographie'), ('Math-info', 'Math-info')], max_length=20, null=True),
        ),
    ]
